project:
  type: book

book:
  title: "AISmartOps"
  author: "Kittipos Sirivongrungson"
  date: today
  repo-url: https://github.com/Lightbridge-KS/ai-smart-ops-notes
  site-url: https://ai-smart-ops-notes-lightbridge.netlify.app
  chapters:
    - index.qmd

format:
  html:
    theme:
      light:
      - cosmo
      dark:
      - darkly
    toc-depth: 4

freeze: auto
